import '../styles/globals.css'
import ScreenViewLogger from './components/screenviewlogger'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        {children}
        <ScreenViewLogger />
      </body>
    </html>
  )
}